---
title: "A2Q2"
author: "Lily Li"
date: "2025-06-09"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Q2
# (a)


```{r}

make_bezier_path_1free = function(x=c(3,5), point2=c(7,5), begin=c(0,0), end=c(10,2))
{
  px = c(begin[1], x[1], point2[1], end[1])
  py = c(begin[2], x[2], point2[2], end[2])
  
  t = seq(from=0, to=1, by=0.01)
  bezier_path_x = (1 - t)^3 * px[1] + 
                  3 * (1 - t)^2 * t * px[2] + 
                  3 * (1 - t) * t^2 * px[3] + 
                  t^3 * px[4]

bezier_path_y = (1 - t)^3 * py[1] + 
                3 * (1 - t)^2 * t * py[2] + 
                3 * (1 - t) * t^2 * py[3] + 
                t^3 * py[4]

  return(list(x=bezier_path_x, y=bezier_path_y))
}

get_path_badness = function(path, factor_acc=10, factor_dist=1, factor_cdir=20) {
  x = path$x
  y = path$y
  dx = diff(x)
  dy = diff(y)
  d2x = c(diff(dx), 0)
  d2y = c(diff(dy), 0)
  acc = sqrt(d2x^2 + d2y^2)
  ds = sqrt(dx^2 + dy^2)
  dir = atan2(dy, dx)
  ddir = abs(diff(dir))
  badness = factor_acc * max(acc)^2 + factor_dist * sum(ds)^2 + factor_cdir * max(ddir)^2
  return(badness)
}

# Makes the data frame to use
x = rep(seq(0,10,0.1), times=101)
y = rep(seq(0,10,0.1), each=101)
df_1a = data.frame(x,y)
df_1a$rho = NA


for (k in 1:nrow(df_1a)) {
  guide1 = c(df_1a$x[k], df_1a$y[k])
  path = make_bezier_path_1free(x = guide1)
  df_1a$rho[k] = get_path_badness(path)
}

head(df_1a)
tail(df_1a)

```

# (b)

```{r}

x_vals <- unique(df_1a$x) 
y_vals <- unique(df_1a$y)

z_matrix <- matrix(df_1a$rho, nrow=101, ncol=101, byrow=FALSE)

contour(x_vals, y_vals, z_matrix,
        xlab = "x (guide point 1)",
        ylab = "y (guide point 1)",
        main = "Contour Plot of Path Badness",
        col = terrain.colors(20))

```

# (c)

```{r}

x <- df_1a$x
y <- df_1a$y
rho <- df_1a$rho

X <- cbind(1, x, x^2, x^3, y, y^2, y^3, x*y, x^2 * y, x * y^2)
Y <- rho

XtX <- t(X) %*% X
XtY <- t(X) %*% Y
beta_hat <- solve(XtX) %*% XtY
beta_hat

model_check <- lm(rho ~ x + I(x^2) + I(x^3) + y + I(y^2) + I(y^3) + I(x*y) + I(x^2*y) + I(x*y^2), data = df_1a)
summary(model_check)$coef


```

# (d)

```{r}

rho_fn = function(x=c(x0, y0)) {
  
  path <- make_bezier_path_1free(x = x)
  rho <- get_path_badness(path)
  
  return(rho)
}


```

# (e)

```{r}

opt_result <- optim(par = c(5, 5), fn = rho_fn, method = "L-BFGS-B", lower = c(0, 0), upper = c(10, 10))

opt_result$par # best x, y
opt_result$value # minimum rho 

```

# (f)

```{r}
make_bezier_path_2free = function(x, begin=c(0,0), end=c(10,2))
{
  point1 <- c(x[1], x[2])
  point2 <- c(x[3], x[4])
  
  
  px = c(begin[1], point1[1], point2[1], end[1])
  py = c(begin[2], point1[2], point2[2], end[2])
  
  t = seq(from=0, to=1, by=0.01)
  bezier_path_x = (1 - t)^3 * px[1] + 
                  3 * (1 - t)^2 * t * px[2] + 
                  3 * (1 - t) * t^2 * px[3] + 
                  t^3 * px[4]

bezier_path_y = (1 - t)^3 * py[1] + 
                3 * (1 - t)^2 * t * py[2] + 
                3 * (1 - t) * t^2 * py[3] + 
                t^3 * py[4]

  return(list(x=bezier_path_x, y=bezier_path_y))
}

```

# (g)

```{r}
rho_fn2 = function(x){
  path <- make_bezier_path_2free(x)
  rho <- get_path_badness(path)
  return(rho)
}

start <- c(3, 5, 7, 5)

opt_result_2free <- optim(par = start, fn = rho_fn2, method = "L-BFGS-B", lower = c(0, 0, 0, 0), upper = c(10, 10, 10, 10))

opt_result_2free$par    # Best positions for (x1, y1, x2, y2)
opt_result_2free$value  # Minimum badness

```
