---
title: "Assignment 1 Q1"
author: "Lily Li"
date: "2025-05-14"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

library(dplyr)
library(ggplot2)


## Q1 
# (a)

```{r}
total_distance_2d = function(x, y) {
  dx = diff(x)
  dy = diff(y)
  distances = sqrt(dx^2 + dy^2)
  return(sum(distances))
}
```

# (b)

```{r}
mean_abs_change_in_direction = function(x, y) {
  dx = diff(x)
  dy = diff(y)
  
  directions = atan2(dy, dx)
  dtheta = diff(directions)
  
  mean_abs_change = mean(abs(dtheta))
  
  return(mean_abs_change)
} 
```

# (c)

```{r}
max_abs_curvature_2d = function(x, y) {
    
    dx = diff(x)
    dy = diff(y)
    
    ddx = diff(dx)
    ddy = diff(dy)
    
    dx_adj = dx[-length(dx)]
    dy_adj = dy[-length(dy)]
    
    numerator = dx_adj * ddy - dy_adj * ddx
    denominator = (dx_adj^2 + dy_adj^2)^(3/2)
    
    curvature = numerator / denominator
    
    return(max(abs(curvature)))
}
```

# (d)
```{r}
p80_percent_acceleration = function(x, y){
  
  dx = diff(x)
  dy = diff(y)
  
  ddx = diff(dx)
  ddy = diff(dy)
  
  acc = sqrt(ddx^2 + ddy^2)
  
  acc_ordered = sort(acc)
  index = round(length(acc_ordered) * 0.8)
  
  if (index == 0) index = 1
  
  return(acc_ordered[index])
}
```

# (e)
```{r echo=FALSE}

mean_velocity_2d = function(x,y){
  dx = diff(x)
  dy = diff(y)
  v = sqrt(dx^2 + dy^2)
  m_v = mean(v)
  return(m_v)
}

  px = c(0,3,7,10)
  py = c(0,5,5,2)
  t = seq(from=0, to=1, by=0.01)
  bezier_path_x = (1-t)^3*px[1] + 3*(1-t)^2*t*px[2] + 3*(1-t)*t^2*px[3] + t^3*px[4]
  bezier_path_y = (1-t)^3*py[1] + 3*(1-t)^2*t*py[2] + 3*(1-t)*t^2*py[3] + t^3*py[4]
  
  t = seq(from=0, to=2*pi, length=101)
  space_path_x = c((t + 4)*sin(3*t), seq(from=0, to=30, length=40), rev(30 - (t + 1)*sin(3*t)))
  space_path_y = c((t + 4)*cos(3*t), seq(from=10.283, to=19.283, length=40), rev(12 + (t + 1)*cos(3*t)))
  
  t = seq(from=0, to=2*pi, length=101)
  heart_path_x = 16*sin(t)^3
  heart_path_y = 13*cos(t) - 5*cos(2*t) - 2*cos(3*t) - cos(4*t)
  
  results = data.frame(
    test_cases = c("Mean Velocity", "Total Distance", "Mean Abs Direction Change","Max Abs Curvature", "80th Percentile Acceleration"),
    Bezier = c(
      mean_velocity_2d(bezier_path_x, bezier_path_y),
      total_distance_2d(bezier_path_x, bezier_path_y),
      mean_abs_change_in_direction(bezier_path_x,bezier_path_y),
      max_abs_curvature_2d(bezier_path_x, bezier_path_y),
      p80_percent_acceleration(bezier_path_x, bezier_path_y)
    ),
    Space = c(
      mean_velocity_2d(space_path_x, space_path_y),
      total_distance_2d(space_path_x, space_path_y),
      mean_abs_change_in_direction(space_path_x, space_path_y),
      max_abs_curvature_2d(space_path_x, space_path_y),
      p80_percent_acceleration(space_path_x, space_path_y)
    ),
    Heart = c(
      mean_velocity_2d(heart_path_x,heart_path_y),
      total_distance_2d(heart_path_x, heart_path_y),
      mean_abs_change_in_direction(heart_path_x, heart_path_y),
      max_abs_curvature_2d(heart_path_x, heart_path_y),
      p80_percent_acceleration(heart_path_x, heart_path_y)
    )
  )
  
   format_signif_df <- function(df, digits = 4) {
     df[-1] <- lapply(df[-1], function(col) signif(col, digits))
     return(df)
   }
  
  formatted_results = format_signif_df(results)
  print(formatted_results)
```

