---
title: "A1Q3"
author: "Lily Li"
date: "2025-05-18"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Q3 

## Q&A:

**a) (2 marks) In your own words. Assuming that the Chicago Quantum Ratio (CQR) is meant to be maximized, what two features of the ideal stock portfolio does this imply?**


A: The maximized CQR implies the stocks have high expected return as well as low risk (quantified by low standard deviation).
\vspace{1em}



**b) (1 mark) What is the size of the population of candiate 60-asset portfolios?**


A: There are approximately 1.15 * (10^18) possible combinations.
\vspace{1em}

**c) (2 marks) In your own words (30 words or fewer), how does the genetic algorithm being applied to stocks work in this instance. Not every detail is needed.**


A: It creates new portfolios by combining an mutating top-scoring ones, then selects the best one using CQNS, repeating this process over generations to improve results. 
\vspace{1em}

**d) (1 mark) Does a hotter 'temperature' in a simulated annealer imply that the solution is more or less likely to settle into a local minima? No explanation is necessary.**



A: Less likely.
\vspace{1em}

**e) (1 mark) Is Chicago Quantum Net Score being minimized or maximized by the D-Wave system in this application? No explanation is necessary.**


A: Minimized
\vspace{1em}

**f) (1 mark) What tendency did the D-Wave system have when finding portfolios that differed from what was desired? No explanation is necessary.**


A: It tended to return smaller portfolios than expected.
\vspace{1em}

**g) (2 marks) In your own word, in comparative analysis, how well did the D-Wave system do at finding the best possible portfolio?**


A: It successfully found efficient and sometimes even ideal portfolio, often outperforming random methods at high-risk levels, but do struggled with the large-sized portfolios.
\vspace{1em}

